# Generated by Django 5.1.1 on 2024-09-17 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_profile_timezone_post_comment_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='author',
        ),
    ]
