# Generated by Django 5.1.1 on 2024-09-18 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_user_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'author')},
        ),
    ]
